server:
  port: 20002

spring:
  application:
    name: nacos-provider-service
  mvc.servlet.path: /base
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/cloudpracdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springclouddb
    username: user
    password: admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.aiguigu.springcloud.entities
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"