server:
  port: 10080
  
eureka: 
  instance:
    hostname: eureka10080.org
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka10081.org:10081/eureka/