server:
  port: 18080
  
spring:
  application:
    name: cloud-consumer-service
  mvc.servlet.path: /consumer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka10081.org:10081/eureka/,http://eureka10080.org:10080/eureka/
  instance:
    instance-id: consumer18080
    prefer-ip-address: true