server:
  port: 10081
  
eureka: 
  instance:
    hostname: eureka10081.org
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka10080.org:10080/eureka/