server:
  port: 4000
  
spring:
  application:
    name: cloud-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abacuszh/cloud2020-config.git
          search-paths:
            - cloud-payment-service
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka10081.org:10081/eureka/,http://eureka10080.org:10080/eureka/
  instance:
    instance-id: springconfig4000
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include:
        - 'bus-refresh'