server:
  port: 8801
  
spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        output:                       # msg provider
          destination: studyExchange  # which exchange to use
          content-type: application/json
          binder: defaultRabbit       # defined several lines above
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka10081.org:10081/eureka/,http://eureka10080.org:10080/eureka/
  instance:
    instance-id: streamprovider8801
    prefer-ip-address: true
    
