server:
  port: 18086
  
spring:
  application:
    name: cloud-consumer-service-openfeign
  mvc.servlet.path: /consumer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka10081.org:10081/eureka/,http://eureka10080.org:10080/eureka/
  instance:
    instance-id: consumer18086
    prefer-ip-address: true
  
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    org.aiguigu.springcloud.service.FeignPaymentService: debug